# Generated by Django 4.2.13 on 2024-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_admin_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('highlights', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
